src/Task/FileSystem/loadShortcuts.php

Fixes #103 (now without handy-dandy GitHub function on the correct base...)

use CopyDir in _copyDir shortcut

---

src/Common/Configuration.php

With this modification the users of the `Robo\Common\Configuration` trait can now specify a default value to use, if none is set.

Adding default value option to the Configuration trait

---

README.md

The variable was called:
```
function testAcceptance($seleniumPath = '~/selenium-server-standalone-2.39.0.jar')
```
At line 61 while it was called $pathToSelenium in the line that I'm modifying.

Fix wrong variable name at docs

---

src/Task/Development/SemVer.php
tests/unit/SemVerTest.php

Had the case where a non writeable .semver file didn't cause the whole task run to exit with an error > 0.

Fail with exception so the task run exits with > 0

---

src/Task/Testing/Codecept.php

As is noted on Codeception, --coverage option is allowed to set custom
file name.
I looked at source code of Codeception project, and this should work if not other --coverage-xxx is included.

Allow to set custom name of coverage file raw name.

---

src/Task/Remote/Ssh.php
tests/unit/SshTest.php

Much cleaner than prefixing `exec('cd /some-dir')`.
Can also be set via static configuration for all future calls:
`\Robo\Task\Remote\Ssh::configure('remoteDir', '/some-dir');`.

Add property remoteDir to Ssh Task

---

docs/tasks/Development.md
src/Task/Development/PhpServer.php

I noticed that in the docs and on the website the code examples for the php server task refer to a method "$this->taskPHPServer" that does not exist, I believe that these references should be updated to "taskServer" and that is reflected in this pull request.

Update php server eamples

---

src/Task/Testing/PHPUnit.php
tests/unit/PHPUnitTest.php

Hi,
--log-xml has been replaced  with --log-junit in 3.4 and removed in 3.5.
vkunz

phpunit: replace log-xml with log-junit 

---

src/Task/File/Concat.php
tests/cli/ConcatCept.php

When concatenating JS files that are NOT minified for development purpose for example that contain comments /*..*/ it will cause syntax errors in the concatenated file.

Fixing concat, it breaks some files if there is no new line.

---

src/Task/File/Replace.php
tests/cli/WriteFileCest.php

I noticed that the current implementation allows to supply an array of arguments for to and from, so that IO access to files can be minimized. I think this is a good feature, but I noticed that there is no test for that.
So I created a little test and a sentence in the documentation for this behaviour.
Best regards Philipp

test Task ReplaceInFile for multiple strings in file

---

docs/started.md

Fixes a wrong name of a variable in the documentation. Is wrong because in previous line is called `$opts` and in the present line is called `$opt` instead

Fix error in array name at documentation

---

src/Common/ExecCommand.php
src/Task/Gulp/Base.php
tests/unit/CodeceptionTest.php
tests/unit/GulpTest.php
tests/unit/PHPUnitTest.php

This should fix issue #129.
I found out that one testcase in the gulp test was testing a part where escapeshellarg from php is used for escaping the name of the task. In windows it's a bit complicated to escape double quotes on the command line (been there ..) So I used the symfony utility which behaves correctly on windows and unix escaping double quotes in commands.
The other fixes were just prepending "call" to batch files and changing from single-quotes to double-quotes
best regards
Philipp

Fix unit-tests on windows

---

src/Task/Development/PhpServer.php
tests/unit/PHPServerTest.php

Wrap `php` command with `exec` to prevent detached PHP server process on e.g. Debian after stopping the background task.
On Debian, the PHP server process currently does not get killed.
The server gets startet correctly:
```
vagrant   4233  pts/0    Ss   09:05   0:00  |       \_ -bash
vagrant   5936  pts/0    S+   10:43   0:00  |           \_ php bin/robo server
vagrant   5937  pts/0    S+   10:43   0:00  |               \_ sh -c php -S 0.0.0.0:8000 -t public
vagrant   5938  pts/0    S+   10:43   0:00  |                   \_ php -S 0.0.0.0:8000 -t public
```
But after finishing the task and stopping the process, the actual PHP server process is still running:
```
vagrant   5938  pts/0    S    10:43   0:00 php -S 0.0.0.0:8000 -t public
```
In this example, only the PID 5937 was killed, not …

PhpServer: Wrap `php` command with `exec`

---

README.md

With the latest version using the task traits is no longer needed. Fixed the watch example as it was still using old code.

Fix watch example in README.md

---

src/Task/Testing/Codecept.php
tests/unit/CodeceptionTest.php

There was a mistake in the skip group option:
As you see, the real name of the option is:
This pull fixes the issue

Fix wrong option to skip groups

---

src/Task/Base/Exec.php
src/Task/Base/Watch.php
src/Task/Development/PackPhar.php
src/Task/FileSystem/CleanDir.php
src/Task/FileSystem/DeleteDir.php
src/Task/Remote/Rsync.php

The task info outputs couldn't seem to make up their mind if they should be capitalised or not. Symfony's console often uses the paradigm where every first-column item is capitalised, and indented items can be whatever makes sense.

Fixed capitalisation of task info output

---

src/Result.php
src/Task/Assets/Less.php
src/Task/Assets/Minify.php

If required package is not installed, detailed detailed error message will be shown:
```bash
Class lessc not found. Please install leafo/lessphp Composer package
```

Add missing packages error reporting to Minify and Less tasks

---

src/Task/Testing/Phpspec.php

Support `--format=tap` for PHPSpec

Allow TAP formatter for phpspec

---

src/Task/Assets/Scss.php
src/Task/Assets/loadTasks.php

An Scss task based on the Less task to add SCSS support with the help of [leafo/scssphp](https://github.com/leafo/scssphp).
Example:
```php
$this->taskScss(
[
'assets/styles/main.scss' => 'dist/styles/main.css'
]
)
->addImportPath('assets/styles')
->addImportPath('vendor/bower-asset')
->setFormatter('Leafo\ScssPhp\Formatter\Compressed')
->run();
```

Add Scss task using leafo/scssphp

---

src/Task/File/Replace.php

The Replace task is always writing to file regardless whether any changes were made or not. This can bring the taskrunner into an inifinite loop if a replaced file is being watched.

Fix Replace task always writing to file

---

RoboFile.php

It seems that the packages tests are not required to run Robo, right ? We may so exlude them (reducing final phar size ~40%).

[Proposal] Exclude packages tests from phar build

---

docs/started.md

Hi!
I've noted that example in docs is not relevant, there is no such trait like use Robo\Task\Exec and seems use Robo\Task\Base\loadShortcuts is enough.

Fix an example in documentation.

---

docs/tasks/Assets.md
src/Task/Assets/ImageMinify.php
src/Task/Assets/loadTasks.php

Minifies images. When the required minifier is not installed on the
system the task will try to download it from the [imagemin](https://github.com/imagemin) repository.
The task supports the following minifiers:
- optipng
- pngquant
- advpng
- pngout
- zopflipng
- pngcrush
- gifsicle
- jpegoptim
- jpeg-recompress
- jpegtran
- svgo (only minification, no downloading)
__Note__ before merging. The task works as intended, generated docs are included, the coding standard was checked. However the class is 603 lines of code and there are a few refactoring possibilities which you might want to consider:
- I am not sure if the `Robo\Task\Assets` namespace is the right one, maybe a new `Robo\Task\Images` namespace would be more future proof.
- The whole `findFiles` method is an exact copy from the …

Add ImageMinify task

---

src/Runner.php

I have the use-case to invoke robo with a relative path. The relativ path passes the first check in <code>:: loadRoboFile</code>, not sue why it did not work for the second file_exists check.

Cast relative path to absolute path

---

tests/unit/RunnerTest.php

This test was failing for me locally; I am on php 5.6, but from reading the PHP docs, it seems this should have always been failing.  In any event, the version here works for me; let's see what Travis has to say.

Make testErrorIsHandled unit test pass.

---

src/Common/IO.php
src/Config.php
src/Runner.php

I needed the full InputInterface, and found out that it's not saved into the Config object. 
With this patch, you can get the input with `$this->getInput()` or `\Robo\Config::get('input')` both directly from the RoboFile.

Added the InputInterface filled with all arguments and options to Robo\Config

---

src/Common/CommandArguments.php
src/Task/Remote/Rsync.php

This PR allows `taskRsync::exclude()` to take an array of patterns, in addition to its traditional parameter value of a single string.
Motivation: sometimes, you might want to call taskRsync with a variable list of locations to exclude.
Before this PR:
```
$rsync = $this->taskRsync()
->fromPath("$tmpDir/drupal-8/")
->toPath($webroot)
->args('-a', '-v', '-z')
->args('--delete');
foreach ($excludes as $exclude) {
$rsync->exclude($exclude);
}
$rsync->run();
```
After this PR:
```
$this->taskRsync()
->fromPath("$tmpDir/drupal-8/")
->toPath($webroot)
->args('-a', '-v', '-z')
->args('--delete')
->exclude($excludes)
->run();
```

Allow Rsync::exclude to accept a list of patterns to exclude.

---

src/Result.php

`$result()` is an odd pattern. Overriding `__invoke()` should be done in instances where the object in question is acting like a php `Callable` object.  Introducing this as a shortcut for an accessor is less desirable than simply using an accessor, as the intent of the code is not obvious.
Since there are better ways to detect errors and recover, we should mark this deprecated for 1.0, and remove it in 2.0.

Mark Result::_invoke() deprecated.

---

src/Task/Remote/Rsync.php
tests/unit/Task/RsyncTest.php

The rsync fails if the source or destination path contains spaces.

Source and destination of the rsync command needs to be escaped

---

src/Task/Archive/Extract.php

When extraction is done within e.g. `/var/www/...`, and then the result moved to `/tmp`, this can fail on a core PHP bug:
https://bugs.php.net/bug.php?id=54097
if `/var` and `/tmp` are on different filesystems.
The simple workaround on that bug report is implemented below; Drush has also historically implemented [a much more complex workaround](http://api.drush.org/api/drush/includes%21filesystem.inc/function/drush_move_dir/6.x).
See also drupal-composer/drupal-project#109 for initial discussion.

Rename a file or directory, coping with cross-partition PHP bug

---

robo
src/Runner.php

Symfony by default calls 'exit', which is bad if you are calling Runner::execute() from some other application, and you'd like to do some extra work after the Runner is done.
This PR moves the call to `exit` to the main `robo` script, so that it is safe for others to call `Runner::execute()`.

No premature exit

---

script.robo
src/Runner.php

This PR allows the user to write standalone Robo scripts that can be executed like other shell scripts. Both multi-command (./myscript mycommand arg) and single-command (./myscript arg) variants are supported.
Requires that `robo` be in your `$PATH`.

Standalone Robo scripts.

---

src/Task/Remote/Rsync.php
tests/unit/Task/RsyncTest.php

I just noticed that the excludeVcs() did not exclude git submodules.
So I added an option for git, svn, hg each.

make excludeVcs() recursive

---

src/Task/Development/SemVer.php
tests/unit/Task/SemVerTest.php

I think the existing implementation of increment does not follow the semantic versioning specification:
- Increment of major must reset minor and patch to 0.
- Increment of minor must reset patch to 0.
Have a look at:
http://semver.org/#spec-item-7
http://semver.org/#spec-item-8

Changed increment method to following semantic versioning specification

---

tests/unit/Task/RsyncTest.php

This PR restores an rsync test that I backed out when merging the DI and PSR-logger stuff.  It looks like an attempt to handle spaces in filenames (e.g. for Windows), so perhaps there was some rsync commit that was also lost somewhere along the way. This bears some investigation.

Restore rsync test backed out in previous merge.

---

src/Task/Archive/Extract.php
src/Task/BaseTask.php
src/Task/Development/Changelog.php
src/Task/Development/GenerateMarkdownDoc.php
src/Task/FileSystem/FilesystemStack.php
src/Task/FileSystem/TmpDir.php
src/TaskAccessor.php
src/Tasklib.php

Add the 'task' convenience method to BaseTask (by way of `use TaskAccessor`), so that Tasks as well as commands (RoboFiles) will be able to use the `$this->task('Foo', $a, $b);` shortcut.
Makes the code easier to read, too.

Move 'task' shortcut to a new TaskAccessor trait.

---

src/Task/Archive/Extract.php
src/Task/Archive/Pack.php
src/Task/Base/ParallelExec.php
src/Task/CommandStack.php
src/Task/Development/Changelog.php
src/Task/Development/GenerateMarkdownDoc.php
src/Task/Development/GitHub.php
src/Task/File/Replace.php
src/Task/File/Write.php
src/Task/Remote/Rsync.php
src/Task/Remote/Ssh.php
tests/unit/Task/CommandStackTest.php

The existence of a magic `__call()` function in a class makes it harder for code analyzers, as they cannot tell if a call to a missing function is or is not handled by the magic function.
DynamicParams makes it a bit faster to write new tasks, and should be maintained for the convenience of external task writers. It's only a little extra code to add to Robo core, though, and having explicit functions will be better overall.
See #295.

Avoid use of DynamicParams trait in Robo core.

---

src/Task/Vcs/GitStack.php
tests/unit/Task/GitTest.php

I added an optional parameter message to the method tag from GitStack. 
Now I can tag with a message like this:
`$this->taskGitStack()->tag($semVer, $message)->run();`
Previously I needed to do it manually with Exec:
`$this->taskExec('git tag -m "' . $message . '" ' . $semVer)->run();`

Added optional parameter message to git tag

---

src/Collection/Collection.php
src/Task/FileSystem/FilesystemStack.php

Also turns off stop on fail for any task that is added via addToCollectionAndIgnoreErrors().
This change is best for consistency, so that collections work correctly.  While this breaks backwards compatibility, any Robo script that relies on stopOnFail defaulting to false could use a little updating anyway.

Make stop on fail the default for FilesystemStack.  BREAKS backwards compatibility.

---

RoboFile.php
src/Common/ProgressIndicatorAwareTrait.php
src/Common/TaskIO.php
src/Contract/ProgressIndicatorAwareInterface.php
src/Runner.php
src/Task/Base/ParallelExec.php
src/Task/Development/PackPhar.php
tests/_data/parascript.php

Tasks can now `implement ProgressIndicatorAwareInterface ` and `use ProgressIndicatorAwareTrait` to have access to a progress bar without having a direct reference to IO or an output object.
The task must still call `startProgressIndicator()` & c. to make the progress indicator go, of course. If the DI container does not have a progress bar, though, then these calls will be no-ops, so programs that do not provide progress displays may still use tasks that utilize them.
The TaskIO trait is aware of the progress interface, and will automatically hide and then re-show the progress bar if a task uses one of the `printTaskInfo` methods to produce output while the progress bar is running.
Note that ProgressIndicatorAwareTrait has a `use Timer` and manages the timer automatically.  Nearly …

Decouple progress bar from tasks that use them

---

RoboFile.php
composer.json
composer.lock
src/Runner.php

Maintain passthrough args as an array rather than imploding into a string. Attach passthrough args to the input object instead of the command object. Handle passing in passthrough args as array values for commands whose last argument is an array.
If this looks good, I will merge the related PR, https://github.com/consolidation-org/annotation-command/pull/3, and tag a new release before merging here.

Fix up passthrough args

---

RoboFile.php
src/Result.php

It is important to exit with an appropriate exit code, so that `$?` is correctly set in Bash, etc.

Set exit code when commands complete.

---

src/Collection/CallableTask.php
src/Collection/Collectable.php
src/Collection/Collection.php
src/Collection/CompletionWrapper.php
src/Contract/CompletionInterface.php
src/Contract/RollbackInterface.php
src/Contract/WrappedTaskInterface.php
tests/cli/CollectionCest.php
tests/unit/Task/CollectionTest.php

And add appropriate type hints to all of them.
Originally, the Collection API was designed to allow clients to just call `add()` on whatever sort of object they had available. However, it is a common pattern to have things such as a `setCode()` method (e.g. Symfony's `Command::setCode()`); I followed this pattern to create `addCode()` et. al., and added typehints to all of these functions.
I don't think there are any (or many) users of Collections right now; if there are any clients that do need to adapt, the typehints will make it easy to figure out what changes are needed.
I think it's important to do this before our stable release; should have been typehinted in the first place.

Introduce TaskInterface and Callable variants for Collection methods

---

RoboFile.php
src/ResultData.php

After reflecting a bit more on #309, I decided that it would be much better and clearer to use `$message` consistently, and avoid introducing `$data['output']`. This PR reflects that change.

Remove $data['output'] from ResultData, and use $message consistently.

---

README.md

You should not suggest using `*` wildcard when requiring a package. This is a bad practice and prevents from breaking BC in major versions, making semver useless

Do not suggest wildcard in composer

---

docs/getting-started.md

I think there was a missing definition of the run-method in the docs.

Fixed missing definition of run-method in the docs

---

CHANGELOG.md
src/Collection/Collection.php
src/Collection/CompletionWrapper.php
src/LoadAllTasks.php
src/Runner.php
src/Task/Archive/Extract.php
src/Task/Archive/Pack.php
src/Task/Assets/ImageMinify.php
src/Task/Development/Changelog.php
src/Task/Development/GenerateMarkdownDoc.php
src/Task/Filesystem/BaseDir.php
src/Task/Filesystem/CleanDir.php
src/Task/Filesystem/CopyDir.php
src/Task/Filesystem/DeleteDir.php
src/Task/Filesystem/FilesystemStack.php
src/Task/Filesystem/FlattenDir.php
src/Task/Filesystem/MirrorDir.php
src/Task/Filesystem/TmpDir.php
src/Task/Filesystem/loadShortcuts.php
src/Task/Filesystem/loadTasks.php

Existing code sometimes uses 'Filesystem' and sometimes uses 'FileSystem'; this is a source of confusion and bugs.  See #331. Symfony uses Symfony/Component/Filesystem; this PR switches to lowercase "system" everywhere.
This may cause some short-term pain with folks upgrading from 0.6.x, but resolving the ambiguity will be better in the long run, I think.

Use 'Filesystem' rather than 'FileSystem' consistently.

---

src/Config.php

Fix some documentation problem around \Robo\Config::getContainer()

Fix some documentation problem around \Robo\Config::getContainer()

---

docs/tasks/Composer.md
src/Task/Composer/Validate.php
src/Task/Composer/loadTasks.php
tests/unit/Task/ComposerTest.php

Add a new task to wrap the "composer validate" command

Add task definition for "composer validate"

---

docs/collections.md
docs/tasks/Filesystem.md
tests/_helpers/CliHelper.php
tests/cli/CollectionCest.php
tests/cli/FilesystemStackCest.php

Should be 'Filesystem' everywhere, for consistencey with Symfony components.
This change was made some time back, but a few instances of 'FileSystem' were missed.

Fix some miscapitalized references to 'FileSystem'

---

src/Task/Vcs/GitStack.php

Commit messages are likely to contain special characters and it's reasonable for them to contain newlines. Both of these can cause trouble with the current hardcoded argument handling.

Escape git commit message argument

---

src/Application.php
src/Collection/Collection.php
src/Common/TaskIO.php
src/Config.php
src/GlobalOptionsEventListener.php
src/Task/BaseTask.php
tests/unit/Task/SvnTest.php

Related to #383, this gives users a way to turn off Robo messages -- which is to say, anything produced by TaskIO.

Add a --supress-messages global option to turn off all task io messages.

---

RoboFile.php

This increases the blacklist of methods to not include by rote in the documentation of every Task that extends BaseTask.
Run `./robo docs` followed by `git diff` to see the effect. I didn't include the generated files in this  PR to avoid conflicts with #393.

Do not document common methods of BaseTask in all of the tasks.

---

RoboFile.php

I noticed that robo.phar is really big (12MB!!). Researching this it quickly turned out that it includes the dev dependencies. Problem is that the previous code had a bug, which lets it pick up currently install dev-dependencies when packing the phar. The PR fixes this, what results in a way smaller phar: ~1.5MB.

Fixed robo.phar to not contain dev dependencies.

---

src/Collection/Collection.php
src/Collection/CollectionBuilder.php
src/Common/ProgressIndicatorAwareTrait.php
src/Common/TimeKeeper.php
src/Common/Timer.php
src/Log/RoboLogStyle.php
src/Result.php
src/ResultData.php
src/Task/Docker/Run.php
src/TaskInfo.php

Remove the 's' from the return value of Result::getExecutionTime(). Add a duration formatter.

Ensure that 'time' is always set in the result of any collection builder

---

.scrutinizer.yml

Scrutinizer does not like our RoboFile. It is too long, too complicated, and coupled with too many components. However, this is expected, because this file is just a sample; it is expected to demonstrate a lot of different things.
Let's exclude it from analysis, since the results are not reflective of Robo as a whole.

Exclude RoboFile.php from Scrutinizer.

---

RoboFile.php
src/LoadAllTasks.php
src/Robo.php
src/Runner.php
src/Tasks.php
tests/_helpers/CodeHelper.php
tests/cli/_bootstrap.php
tests/unit/ApplicationTest.php

Provide Robo's standard service list. This makes it easier for external programs that use Robo as a library to configure their DI container. It was a mistake to move this list to a non-static method in RC1.

Create a static Robo::standardServices() method

---

src/Task/Filesystem/FilesystemStack.php

Add return type to FilesystemStack @method tag to enable auto complete when chaining methods in IDEs, eg `$this->taskFilesystemStack()->copy($source, $destination)->run();`.

Add return type to @method tag to enable autocomplete

---

src/Task/Archive/Pack.php

As PHPstrom is always complaining about return types I had to fix this to get rid of the warning.
I also fixed the missing param while calling Result::error().

fixed some docs e.g. the return type of the run() method

---

CHANGELOG.md
script.robo

It was a misnomer to call 'Robo scripts' "standalone", because these scripts require the Robo application in your $PATH, and this is not part of the script.
We should reserve the term "standalone" for applications derived from Robo that contain the entire Robo application, e.g. by requiring Robo in composer.json.

Rename 'Robo standalone scripts' to 'Robo scripts'.

---

docs/tasks/Testing.md
src/Task/Testing/Atoum.php

Fixes a misleading reference to non-existent `file()` method in Atoum doc as well as a minor typo. Refer to individual commit messages for full details.

Atoum documentation fixes

---

src/Robo.php
src/Runner.php

Allow applications using Robo as a framework to supply thier own application name and version (if they let Robo set up the DI container), or even a complete application object (if they set up their own DI container).
This was an oversight.

Supply application name and version when using Robo as a framework

---

src/Collection/CollectionBuilder.php
src/Common/IO.php
src/Common/InputAwareTrait.php
src/Common/OutputAwareTrait.php
src/Common/ResourceExistenceChecker.php
src/Config.php
src/Contract/IOAwareInterface.php
src/Robo.php
src/Runner.php
src/Task/Base/SymfonyCommand.php
src/Task/Composer/Base.php
src/Tasks.php
tests/unit/Common/ResourceExistenceChecker.php
tests/unit/OutputTest.php
tests/unit/Task/ApiGenTest.php
tests/unit/Task/AtoumTest.php
tests/unit/Task/BowerTest.php
tests/unit/Task/CodeceptionTest.php
tests/unit/Task/ComposerTest.php
tests/unit/Task/ExecTaskTest.php
tests/unit/Task/GitTest.php
tests/unit/Task/GulpTest.php
tests/unit/Task/HgTest.php
tests/unit/Task/NpmTest.php
tests/unit/Task/PHPServerTest.php
tests/unit/Task/PHPUnitTest.php
tests/unit/Task/PhpspecTest.php
tests/unit/Task/SvnTest.php

Rename getOutput() and getInput() to output() and input(); remove globals from the IO trait, and build IO off of InputAwareTrait and OutputAwareTrait.
`getInput()` and `getOutput()` methods maintained for backwards compatibility.

IO interface

---

src/Task/Base/loadShortcuts.php

Any RoboFile using the _exec() shortcut is broken it seems.
E.g.
```
$  robo build
Class taskExec does not exist
```

Fixes loading the _exec() shortcut. 'Class taskExec does not exist'.

---

docs/tasks/Testing.md
src/Task/Testing/PHPUnit.php

Unfortunately, PHPUnit does not support passing a list of test files
to run via the command-line interface. However, the current
implementation of the PHPUnit task allowed passing an array of files
to its `files()` method, which it would then append to the command as
a string of comma-delimited files, which would cause the PHPUnit
executable to fail.
The PHPUnit executable supports either a path to a directory
containing multiple test files or a path to a single test file as a
command-line argument.
This fixes the issue by allowing only a single string to be passed via
`files()`.
Signed-off-by: Antoine Busque <antoine.busque@pillrcompany.com>

Fix: disallow passing multiple test files to PHPUnit via files()

---

src/Common/BuilderAwareTrait.php
src/Contract/BuilderAwareInterface.php

so that it does not appear as a command in RoboFiles.
Simple bugfix.

Protect BuilderAwareTrait::collectionBuilder() 

---

src/Collection/Collection.php
src/Exception/TaskExitException.php
src/Result.php
src/Runner.php
tests/_helpers/CodeHelper.php
tests/src/TestRoboFile.php
tests/unit/ResultTest.php
tests/unit/RunnerTest.php

Make stop on fail throw an exception, so that it will be testable. Make stopOnFail and collections interact better - stop on fail can be used to interrupt a collection, which will still clean up on failure, and stop execution of further code.

Add a test for Result::$stopOnFail.

---

CHANGELOG.md
src/Common/CommandArguments.php
src/Task/Remote/Rsync.php
tests/unit/Task/ApiGenTest.php
tests/unit/Task/RsyncTest.php

One more change, for consistency.
Arguments passed to `->arg()` and values passed to `->option()` are always escaped. This is better and safer, and makes option() and optionList() consistent. `->rawArg()` is available for clients that have a value that has already been shell-escaped.
Note that entire command strings, e.g. those passed to the constructor of Exec(), are expected to be already escaped by the client.

Always escape arguments CommandArguments.

---

docs/getting-started.md
src/Common/IO.php
tests/src/TestRoboFile.php
tests/unit/RunnerTest.php

The SymfonyStyle class is very popular; see the [introductory documentation](http://symfony.com/blog/new-in-symfony-2-8-console-style-guide) for details.
This is how folks expect to do IO with Symfony Console applications nowadays, so we should provide ready access to it from RoboFiles.  It might even be a good idea to update the documentation to use SymfonyStyle for IO.
The existing methods in the IO trait may remain for backwards compatibility with Robo 0.x; perhaps these should be deprecated and removed in 2.x.

Add accessor for SymfonyStyle object.

---

src/Collection/Collection.php
src/Collection/CollectionBuilder.php
src/Collection/Element.php
src/Config.php
src/Result.php
src/Robo.php
src/Runner.php
src/Task/Remote/Ssh.php
src/Task/Simulator.php
src/Task/Testing/PHPUnit.php
tests/src/RoboFileFixture.php
tests/unit/RunnerTest.php

Allow CollectionBuilder, Collection and Simulated tasks to be used by tasks (e.g. Remote\Ssh) that require a CommandInterface.

Fixes #442: Pass a collection to Remote\Ssh

---

src/Application.php
src/Common/TaskIO.php
src/Config.php

For the casual Robo user, this option is not sufficiently different than --quiet. Applications that wish to alter the way that Robo handles status messages should override Robo's default container as described in docs/framework.md.

Backs out #396: Remove --supress-messages.

---

src/Task/Testing/PHPUnit.php

Fix a bug in PHPUnit task: specifying a directory caused infinite loop.
The dir function is currently only calling itself, causing an infinite loop. I'm assuming the intention was to call ExecOneCommand::dir instead. 
This fix relieves the method naming conflict and calls the aliased method.

Fix a bug in PHPUnit task: specifying a directory caused infinite loop.

---

src/Task/Assets/Minify.php

Fixes #254.
If the minified size of a file was greater than the original size a PHP
error would be thrown. This would happen if you tried to minifed files
that had already been minifed.
This fix stops the minifed size being greater than the original size.

Fix PHP error in Minify

---

RoboFile.php
src/Robo.php

Keep the version at '-dev' between releases
To reduce confusion, this PR ensures that the Robo version will always end in '-dev' between releases.  The '-dev' modifier is removed during the release process, and put back again at the end.  The --beta flag is still supported; it will advance through beta1, beta2 and so on, if used.
Major and minor version advances will still need to be done by hand prior to release.
Changes are all to the main RoboFile, which has no tests; therefore, there are no tests in this PR either.

Improve Robo version management

---

src/Common/IO.php

In attempting to override IO methods such as yell() or ask(), I found that I was stymied by various IO methods having private access. Perhaps there is a reason for this, but I found it useful to be able to call methods such as formatQuestion() from my own overridden confirm() method. 
This makes it much easier, and DRYer, to override output formatting.

Change access to protected for IO methods.

---

src/Common/ExecCommand.php

This allows a globally installed Robo to resolve an executable
installed locally in `vendor/bin` under the current working directory.
The use case that lead me to this fix is having a locally installed phpunit, and a globally installed robo. Prior to the fix, it would fail to resolve the phpunit executable, whereas it resolved it just fine prior to version 1.x.
Signed-off-by: Antoine Busque <antoine.busque@pillrcompany.com>

Fix: look for project bin directory in current working directory

---

src/Task/File/TmpFile.php

Fix a typo in the name of a variable.
The 3rd parameter of the constructor was ignored. An undefined variable was used instead but the usage of empty() silenced the error.

Fix: use baseDir when provided as a parameter in the TmpFile constructor

---

docs/tasks/Base.md
src/Common/ExecCommand.php
src/Task/Base/Exec.php

This PR introduces two new abilities:
- Use exec task _without_ printing command, working directory, and timer. This allows the task to be truly silent.`$this->taskExec("something")->silent(true)->run();`
- Use exec task to print output but _not_ print metadata, like the timer. This makes the call a bit more "passthru". `$this->taskExec("something")->printOutput(true)->printMetadata(false)->run();`

Adding printMetadata() option to exec command.

---

src/Task/Base/Exec.php

Currently all processes started with `Exec` read from `/dev/null` and can't be interacted with. This PR allows to pass a string/resource to the process and enables optional interaction.
Use-cases could be generators or password-prompts during deployment.
Will close #391

Allow to run exec tasks with input and/or interaction

---

src/Task/StackBasedTask.php

Currently, slashes are displayed as escaped when printed via printTaskProgress(). This is difficult to read and does not seem necessary since it's intended for humans.

Making printTaskProgress() json ouput more legible.

---

src/Collection/CollectionBuilder.php
src/Task/Development/SemVer.php

Fixes the SemVer task, broken in Robo 1.x when used with the collection builder.
The collection builder was calling `inflect()` on tasks that neither needed nor were able to `inflect`. Now, this step is skipped for simple tasks that do not inflect.

Do not call inflect unless the task needs & can do it.

---

appveyor.yml

Add Appveyor testing for Windows
This PR contains an Appveyor configuration file for doing Windows CI testing. I'm having trouble selecting projects in organizations in Appveryor, but I [ran these tests in a forked Robo in my own account](https://ci.appveyor.com/project/greg-1-anderson/robo/build/1.0.4) successfully.

Add appveyor.yml for Windows testing.

---

src/Task/Development/Changelog.php

Fixed function name used by the Changelog task.
The Changelog task was failing because it called the function taskReplace. The correct name of the function to call is taskReplaceInFile.

Fix function name used by Changelog task

---

src/Task/Development/GitHubRelease.php

Use name variable for Github release name.
The GithubRelease task provides a name method to set the release name, but when creating the release, it uses the tag variable instead of the name variable.

Use name variable for Githubrelease name

---

src/Collection/CollectionBuilder.php
src/Common/OutputAdapter.php
src/Common/TaskIO.php
src/Common/VerbosityThresholdTrait.php
src/Contract/OutputAdapterInterface.php
src/Contract/VerbosityThresholdInterface.php
src/Log/ResultPrinter.php
src/Robo.php
src/Task/Base/Exec.php
src/Task/BaseTask.php
tests/src/RoboFileFixture.php
tests/unit/RunnerTest.php

Allows commands to control the verbosity level at which different tasks will emit their progress notices et. al.
Commands can now call `$builder->setRequiredVerbosity(OutputInterface::VERBOSITY_VERBOSE)` (or other verbosity constant) to suppress output of tasks when command executed below a certain verbosity level.
For Robo scripts that are used from CI servers, it is important to be able to suppress the output of particularly talkative commands (e.g. `composer update`, `git add -A .` et. al.), to avoid being unable to see more interesting messages later, should the CI server truncate the output. This PR gives commands the ability to set a minimum verbosity level on a task-by-task basis, so that the lengthy command output may be easily displayed should the command fail …

Add TaskIO::setVerbosityThreshold()

---

.travis.yml

Add phpunit 7.1 to test matrix.

Add php71 to test matrix.

---

src/Collection/CollectionBuilder.php

Make it possible to name a task by providing a second argument to `collectionBuilder::addCode()`.
See https://github.com/consolidation/Robo/issues/540
```
$ robo  sniff src/Collection/CollectionBuilder.php
[Exec] Running ./vendor/bin/phpcs --standard=PSR2 -n src/Collection/CollectionBuilder.php
[Exec] Done in 0.143s
```

Fix the signature of the addCode() wrapper so that we can name a task.

---

src/Task/ApiGen/ApiGen.php
tests/unit/Task/ApiGenTest.php

Allows users to run `apigen generate` more simply
If a user passes no operation to the constructor, this change will default to generate. Passing an operation (and optionally arguments) will now separate these out into the appropriate class variables. If a user passes an operation to `arg()` or `args()`, it will overwrite the current operation so that only one will be assembled into the final command.

Default apigen operation to 'generate'

---

.travis.yml
composer.json
composer.lock
examples/RoboFile.php
src/Common/ExecTrait.php
src/Common/ProgressIndicatorAwareTrait.php
tests/unit/OutputTest.php

Symfony 3.2.6 deprecates a method we use in testing.

Update to Symfony 3.2.6 et. al.

---

docs/extending.md
src/Collection/CollectionBuilder.php
src/Common/ProcessExecutor.php
src/Robo.php
src/Runner.php
tests/_helpers/CliHelper.php
tests/unit/ApplicationTest.php

Remove call to undocumented two-parameter `$container->get('ref', [$arg]);`
League/Container allows objects to be fetched from the container using a two-parameter 'get' method. For objects that are not shared, this method will construct a new object using the parameters provided. However, this method is undocumented, and PSR-11 does not allow clients of the container to provide parameters for object construction, all of which are presumed to be provided from the container.

Add factory methods for CollectionBuilder and ProcessExecutor.

---

src/Common/CommandArguments.php

This permits a user to define the separator and execute commands like `command --option=value`.

Add $separator parameter to ->option() method.

---

src/Task/Composer/Base.php

Added the 'ignore-platform-reqs' option to the composer tasks options for more convenient use.

Add Ignore Platform Reqs to Composer Task

---

docs/tasks/Filesystem.md
src/Task/Filesystem/CopyDir.php
src/Task/Filesystem/loadTasks.php

Currently, the `CopyDir` task does not allow a user to specify whether or not destination files should be overwritten in the event that they are newer than the source files (a la the `overwrite` option provided in [Phing's copy task](https://www.phing.info/docs/guide/trunk/CopyTask.html). This pull request adds in an optional `$overwrite` parameter to the `CopyDir` task that defaults to `true` to ensure backwards compatibility (could consider changing the default to `false` for a major release).
To achieve the above behavior, `CopyDir` was modified to use the existing symfony `fs` object's `copy` method instead of what it is currently using - php's built in `copy` method.

Modify CopyDir task to leverage symfony Filesystem copy.

---

src/Common/ExecTrait.php

Make detectInteractive() chainable for taskExec().

Make detectInteractive() chainable.

---

src/Common/ExecTrait.php
tests/cli/ExecCest.php

Currently, `detectInteractive()` does not work as intended because its check for `isset($this->interactive)` will always be return true.

Setting $this->interactive to NULL by default.

---

src/Task/Testing/Codecept.php
tests/unit/Task/CodeceptionTest.php

- Fixes a bug
- Has tests that cover changes
Changed suite and testname in codecept task command - now they are handled as simple options.
**Before fix**: suite and testname always be in the end of the command. This behaviour breaks some rawArg() , e.g. "> log", "| tee log". 
**After fix**: suite and testname are treated like simple options.

Codecept suite and testname fix

---

src/Task/Docker/Base.php

Removes the explicit call to `printTaskInfo()` inside Docker tasks since it effectively duplicates a similar call made implicitly by `ExecTrait`.
This seems to resolve consolidation/Robo#576.

Remove superfluous printTaskInfo() call

---

src/Common/ExecTrait.php
src/ResultData.php
src/Task/CommandStack.php
tests/_helpers/SeeInOutputTrait.php

Ensures the output from said command is returned in the exec result.
If a CommandStack has only a single command, always return the result of that command with its output.
The CommandStack throws away command output when it runs multiple commands individually in `stopOnFail` mode. Commands are run individually in this mode so that the exact command that failed is identified in the result when there is a failure. The results from the command are discarded when doing this because it is inconvenient to merge together multiple Result objects under the current implementation. Result objects print a result message in their constructor, which is a poor time to be printing output; however, the implementation of progress output was easier that way, and there is a focus on …

Fixes #574: In 'stopOnFail' mode in CommandStack with a single command.

---

docs/getting-started.md

- Fixed typo in documentation.
- Updated `$PATH` to appear as code.
- Updated a single code example to be formatted as code.

Fixed typo in getting-started docs.

---

composer.json
src/Collection/Collection.php
src/Result.php
src/ResultData.php
src/State/Data.php
src/Task/Development/SemVer.php

Allow semver task to be used with strings. Just exercising the CollectionBuilder on a task that does not implement BaseTask.

Enhance SemVer task so that it can be used with files or strings.

---

appveyor.yml
docs/getting-started.md
src/Collection/CollectionBuilder.php
src/Common/ConfigAwareTrait.php
src/Task/BaseTask.php
tests/_data/robo.yml
tests/unit/ConfigurationInjectionTest.php

The documentation on `Robo\Task\Remote\Ssh::configure` was inconsistent with the implementation, which did not match up with how the container builder was injecting task configuration. 
This breaks b/c, but only for the config system, which is still experimental (b/c breaking changes may happen until 1.1.0).

Make implementation of task configuration keys consistent with docs

---

CHANGELOG.md
docs/getting-started.md
src/Collection/CollectionBuilder.php
src/Config/Config.php
src/InjectConfigEventListener.php
tests/_data/falback-task-config-robo.yml
tests/unit/ConfigurationInjectionTest.php

Adds 'configuration fallback' feature that allows commands and tasks to share configuration.
Example from documentation:
Command groups may also share configuration options. For example, if you have commands `foo:bar`, `foo:baz` and `foo:boz`, all of which share a common option `color`, then the following configuration will provide the value `blue` to `foo:bar` and `foo:baz`, and the value `green` to `foo:boz`:
```
command:
foo:
options:
color: blue
boz:
options:
color: green
```

Add configuration fallback feature.

---

src/Task/Base/ParallelExec.php
tests/unit/Task/ParallelExecTest.php

Add an option to parallelExec to wait for a period of time (in seconds) after starting one process and before the next one.
An example usage would be:
```
$this->taskParallelExec()
->process($this->taskCodecept(...))
->process($this->taskCodecept(...))
->waitInterval(5)
->run();
```

Add an option to wait an interval of time between parallel processes

---

src/Task/Testing/Codecept.php
tests/unit/Task/CodeceptionTest.php

- [+] Fixes a bug
- [+] Adds a feature
- [-] Breaks backwards compatibility
- [+] Has tests that cover changes
This feature is critical for parallel running. Without this, codeception
rebuilds some generated files in each sub-process. This affects to
concurrent writing to the same files the same content. Run fails.
To this topic there are several bugs in neighbor repos:
First mention at https://github.com/Codeception/Codeception/issues/2054
Then comes here https://github.com/Codeception/robo-paracept/issues/28
And here https://github.com/Codeception/Codeception/pull/4148 but this is not a fix for the problem, just workaround.
My solution adds codeception functionality to Codeception task at Robo project. Using it, we will stop getting errors.
But you should remember, …

Add noRebuild() method for Codeception run command

---

src/Robo.php

Changed variable being used to export config
The `$loader` variable only contains the last `yml` configuration file loaded, while the `$processor` variable contains them all. By changing `$loader->export()` to `$processor->export()` all of the loaded configuration files are loaded into the configuration object instead of just the last one.

Fixes #611: Issue-611: Fix robo.yml loader by exporting processor instead of loader

---

src/Task/Testing/Codecept.php
tests/unit/Task/CodeceptionTest.php

- [-] Fixes a bug
- [+] Adds a feature
- [-] Breaks backwards compatibility
- [+] Has tests that cover changes
Add failGroup() method for Codeception run command
This feature is major for parallel running. Without this, codeception
puts failed tasks to the same file, each thread rewrites file. With
this config we can send fails to different files and aggregate them
later manually.

Add failGroup() method for Codeception run command

---

src/Task/Filesystem/loadShortcuts.php

I've noticed when using _rename shortcut from FS tasks, the overwrite parameter is silently ignored, even thought it's present in the task itself. Adding it as it doesn't break backwards compatibility and is potentially useful to shortcut users.

Add overwrite argument to Filesystem\loadShortcuts.php::_rename

---

src/Task/Docker/Base.php

Fix Robo\Task\Docker\Base to implement CommandInterface as it is already an implementation of the above. With the fix you can use Docker commands in SshExec tasks and other tasks expecting a CommandInterface or a string command let's say if you plan to proxy a docker command execution to a remote machine

Fix Robo\Task\Docker\Base to implement CommandInterface

---

docs/tasks/Development.md
src/Task/Development/Changelog.php

* Adds `setBody()` to permit users to set raw text directly and bypass the default text processing of the log.
* Adds `setHeader()` likewise.
* Splits some logic into separate methods to make it easier to override in child classes.

Make Changelog task more flexible.

---

composer.json
composer.lock
robo.yml
src/Robo.php

Adjusts the order that hooks are added so that dynamically added options can still participate in config injection.

Inject option order

---

src/Common/ExecTrait.php

Using `tastExecStack()` to execute multiple commands creates output like:
```
[ExecStack] Running /Users/matthew.grasmick/Sites/acquia/blt/../blted8/vendor/bin/blt ci:travis:init -v && /Users/matthew.grasmick/Sites/acquia/blt/../blted8/vendor/bin/blt ci:pipelines:init -v && /Users/matthew.grasmick/Sites/acquia/blt/../blted8/vendor/bin/blt acsf:init:hooks -v && /Users/matthew.grasmick/Sites/acquia/blt/../blted8/vendor/bin/blt setup:cloud-hooks -v && /Users/matthew.grasmick/Sites/acquia/blt/../blted8/vendor/bin/blt config:dump && /Users/matthew.grasmick/Sites/acquia/blt/vendor/bin/robo sniff-code --load-from /Users/matthew.grasmick/Sites/acquia/blt && /Users/matthew.grasmick/Sites/acquia/blt/../blted8/vendor/bin/blt vm --no-interaction --yes -v && …
```

Adding display formatting to ExecStack commands.

---

src/Task/Remote/Ssh.php

SshCommand is using sprintf to return a formatted command, but it's not actually sing any variables and basically just relies on inline variable interpolation. I think it is redundant and it's creating some other issues with string formatting, as now you have to escape your % characters in your options.
Please see the following usage scenario:
```
$this->taskSshExec('company.com', 'user')
->option('-o', 'ProxyCommand ssh -A -q user@bastion.company.com nc %h %p');
```
If you use sprintf, you will have to escape all % chars with another %. But since sprintf is not doing any formatting now, I propose to replace it with string interpolation.
**Possible breaking change:**
This may be a breaking change for someone who already relied on sshCommand and was already escaping the …

Remove unnecessary string formatting for sshCommand

---

.travis.yml
RoboFile.php
composer.json
composer.lock
scenarios/install
scenarios/symfony2/composer.json
scenarios/symfony4/composer.json
scenarios/symfony4/composer.lock
scripts/composer/ScriptHandler.php
src/Task/Composer/Base.php

The 'composer scenarios' changes to improve testing on Symfony 2 - 4 removed the fixup code for php 5.5. This workaround is still necessary, and removing it broke the Robo release scripts.

Restore 5.5 fixup

---

src/Collection/TaskForEach.php
src/Collection/loadTasks.php
tests/_helpers/CliHelper.php
tests/cli/ForEachCest.php

Issue #656: Add \Robo\Collection\TaskForEach::setIterable()

---

composer.json
examples/src/Robo/Plugin/Commands/ExampleCommands.php

Continuation of #671.
Implements Robo examples as a plugin. With this implementation, examples are available from a git checkout of Robo, but are not available in the phar.

Implement the example RoboFile as a Robo plugin.

---

docs/getting-started.md

The right way to access robo config is `\Robo\Robo::config()` and not `Robo::config()`

Typo in README

---

src/Task/Remote/Rsync.php
tests/unit/Task/RsyncTest.php

When specifying remoteShell() option with rsync, the result is double-escaped. For example:
```
$this->taskRsync()
->fromPath('.')
->toHost($server)
->toUser('user')
->toPath('/var/www')
->remoteShell('ssh -i /home/user/.ssh/deploy')
->run();
```
Generates:
```
Running rsync --rsh ''\''ssh -i /home/user/.ssh/deploy'\''' . 'user@192.168.1.1:/var/www'
```
This changeset fixes the double escape and adds a test:
```
Running rsync --rsh 'ssh -i /home/user/.ssh/deploy' . 'user@192.168.1.1:/var/www'
```
Did not test on Windows (do not have the ability to do so easily).

Fix double escape when specifying a remoteShell with rsync. Add test.

---

docs/tasks/Base.md
src/Task/Base/Watch.php
tests/_bootstrap.php
tests/unit/Task/WatchTest.php

Adds ability to set multiple events to file/dirs.
Robo has hard coded watching for modification event only which is not firing when files are added or removed. To give possibility to react on this kind of changes monitor function now can take third argument which stands for events. Like in paths it can be array or single value. To maintain backward compatibility default event was set to modify event. This PR is related to #650.
Usage:
```php
<?php
$this->taskWatch()
->monitor(
'src', 
function() {
$this->taskExec('phpunit')->run();
},
\Lurker\Event\FilesystemEvent::CREATE
)->run();
$this->taskWatch()
->monitor(
'src', 
function() {
$this->taskExec('phpunit')->run();
},
[
\Lurker\Event\FilesystemEvent::CREATE, 
\Lurker\Event\FilesystemEvent::DELETE
]
)->run();
```

Events as third parameter in watch function

---

src/Runner.php

Shebang handling could throw an error, e.g. when the first parameter to a Robo function was something like `git://git.drupal.org/project/drupal.git`

Fix overzealous shebang function

---

src/Task/Composer/loadTasks.php

There are a few incorrect `@return` values in `\Robo\Task\Composer\loadTasks`.

Correct Doxygen in \Robo\Task\Composer\loadTasks.

---

robo

\Phar::running() is documented to return nothing in the stub. This method DOES
work when the phar is built with https://github.com/humbug/box, but it behaves
as documented when Robo builds its phar with the standard Phar APIs (which is
to say that it returns an empty string).
When running as a phar, __FILE__ will return whatever the current filename for
the phar is, so the documentation's suggestion to use __FILE__ in place of
\Phar::running() also does not work. However, the path that we compiled the
phar with, 'phar://robo.phar/...' always works.  We therefore use that first
if it exists.
The phar was broken in 1.3.2. This fixes it.

Fix the main Robo script entrypoint to work as a phar.

---

tests/cli/CollectionCest.php

Adds to the rollback order test with a nested collection with rollbacks.

Ensure nested collections with rollbacks preserve correct order of execution

---

docs/collections.md
src/Collection/Collection.php
src/Exception/AbortTasksException.php
src/Exception/ForcedException.php
tests/cli/CollectionCest.php

Adds a new exception `ForcedException` for forcefully aborting a rollback or completion.

Allow for aborting completions or rollbacks.

---

.scenarios.lock/symfony2/composer.json
.scenarios.lock/symfony4/composer.json
.scenarios.lock/symfony4/composer.lock
LICENSE
composer.json
composer.lock
examples/src/Robo/Plugin/Commands/ExampleCommands.php
src/Application.php
src/Common/IO.php
src/Contract/IOAwareInterface.php
src/Robo.php
src/Symfony/IOStorage.php
src/Symfony/SymfonyStyleInjector.php

The existing Robo DI container adds a reference to the $input and $output objects. Application::run() also takes $input and $output as parameters. What happens, then, if you want to call Application::run() multiple times with different $input and $output objects?
The answer is that some of the code will use the correct $input and $output objects, but other code will use whatever $input and $output were injected into the DI container, which would produce incorrect results. It would be better to simply not have any reference to $input and $output in the DI container at all; however, a lot of objects inject the logger, which needs $output, and a lot of commands implement IOAwareInterface, which has references to both.
This PR allows commands to take a SymfonyStyle object …

Improved param injection

---

src/Common/IO.php

We need a trivial helper function to give us access to stderr (when available)

Add stderr() convenience method to Robo\Common\IO.

---

docs/framework.md

In command line PHP scripts the variable $argv is prefilled with command line parameters to the script. The deleted line is doubling this and in addition, most coding style tools make it an issue to use unfiltered globals.
Filtering that global (like in `$argv = filter_input_array($_SERVER['argv'])`) results in plenty of errors. 
Lastly it probably results in validation errors because $argv is a reserved variable. 
see http://php.net/manual/en/reserved.variables.argv.php
see consolidation/Robo#839

Use $argv directly in framework documentation

---

src/Task/Base/Watch.php

See consolidation/Robo#845 for this. Requested was a way to know which file(s) are changed when calling the `$callable` parameter. This is available via Lurker, but not documented yet.

Add sample with changed file handling to Base/Watch documentation

---

src/Common/IO.php

Allow a default argument for confirm() prompts so they can be run non-interactively (BLT currently has to override this method to allow a default argument). This also aligns more closely with the super method in Symfony, which takes a default argument.
It's a somewhat trivial change, not sure if it needs dedicated tests.

Fixes #849: Allow default argument for confirm() questions.

---

src/Collection/CollectionBuilder.php

There was a typo in a method name in the CollectionBuilder class. Thankfully it is a protected method so it should be somewhat safe from API breaks.

Rename callCollectionStateFuntion to callCollectionStateFunction

---

src/Task/Assets/ImageMinify.php

If the given imagefile is not one of the defaults (png/jpg/gif/svg) and no minifier was passed to the ImageMinify task a warning for an undefined variable is show.
Prevent this by setting an empty string to the beginning of the file check.
Refs #852
Adds an empty variable string to the beginning of the loop to check for matching minifiers. This will prevent trying to access a non existing variable later on.
This bugfix is for the master (Development version 2.x).
It may also be cherry-picked to the `1.x` branch as well (I could send a second PR as well).

ImageMinify: Prevent undefined variable error

---

src/Task/Assets/ImageMinify.php

Followup for PR #853 
Backports the fix for issue #852 into 1.x branch.
Refs #852
See #853

ImageMinify: Prevent undefined variable error (#852) (backport for 1.x)

---

docs/extending.md
src/Runner.php
tests/plugins/Robo/Plugin/Commands/ThirdCustomCommand.php
tests/unit/ClassDiscovery/RelativeNamespaceDiscoveryTest.php

This PR allows command classes to end in both Commands or Command, and (because of PSR-4) the files in Commands.php or Command.php
In my head it makes more sense to have a command file/class per command, in stead of one with multiple. You could perfectly do this right now, but the filename wouldn't make sense. It's a bit of a nitpick, but it just seems cleaner in my mind.

Allow command classes to end in Commands or Command.

---

README.md

A tiny markdown formatting fix/improvement to the README

Tiny formatting fix in README

---

.github/pull_request_template.md

I often run into pull requests that add or fix the documentation. This should be an option in the pull request template.

Adding documentation as option to pull_request_template.md

---

docs/getting-started.md

It appears this line needs to be beautified.
Looks like that line wanted to be displayed as code.

Add missing code formatting to sample code

---

src/Task/Assets/Scss.php

Changed out leafo/scssphp to scssphp/scssphp as leafo/scssphp is archived, and development is continuting at scssphp/scssphp.
Development is continuting at scssphp/scssphp, see https://github.com/leafo/scssphp and new repo https://github.com/scssphp/scssphp.
Will need to update documentation on robo.li: https://robo.li/tasks/Assets/#scss

Changed leafo to scssphp as leafo is archived

---

src/Task/Assets/ImageMinify.php

Fix ERROR: Undefined variable: target_dir
Wrong variable name

Fix variable error

---

src/Common/ExecTrait.php

Fixes #922 by just matching visibility between these traits.
Would love a backport to 1.x and new release after this is fixed.

Fixed #922: PHP 7.4 compatibility.

---

docs/tasks/Composer.md
src/Task/Composer/Install.php
src/Task/Composer/RequireDependency.php
src/Task/Composer/Update.php

Added the ability to use composer install, update and require tasks with the `--no-suggest` option
```php
$this->taskComposerInstall()->noSuggest()->run(); // composer install --no-suggest
```
Regarding tests, i found some related to composer tasks in https://github.com/consolidation/Robo/blob/master/tests/unit/Task/ComposerTest.php but i haven't been able to run them. I can add some if required but i would need some guidance on how to do it.
Thanks

added the --no-suggest option to composer tasks

---

src/Task/Development/GitHub.php

See #936: Github has deprecated the usage of access_token via a query parameter as Robo currently uses for Github requests. You should use an authorization header with the access token instead.
This is untested but I'm pretty sure should work.

Fixes #936: Github access_token via query parameter is deprecated.

---

src/Task/File/Replace.php

When using [Replace with Regexp](https://robo.li/tasks/File/#replace) there is no possibility to add a limit to the replaced items. This would be useful for instance when I replace version numbers in the DocBlock of fields and we want to replace only a single occurence.
for consolidation/Robo#945

Add a limit to replace via regexp

---

docs/tasks/Docker.md
src/Task/Docker/Build.php
tests/unit/Task/DockerTest.php

Adds a new toggle for enabling Docker Buildkit.
If enabled, the required environment variable will be prepended to the command.
Commits should be squashed. :)

Docker builds with Buildkit

---

src/Runner.php

In instances where the simple default config rules are in use, allow for config files to be loaded from the root of the app when Robo is in the vendor directory.

More flexible config parsing

---

src/Task/Archive/Pack.php

Class ZipArchive does not have a constructor and must be instantiated without any parameters.
https://www.php.net/manual/en/class.ziparchive.php
props. @phpstan

Class ZipArchive does not have a constructor

---

src/Common/BuilderAwareTrait.php

Fixes the BuilderAwareTrait.php to prevent fatal error
Added a null check and throwing an exception which can be caught in user code unlike fatal errors.
Fixes the BuilderAwareTrait.php to prevent Fatal Error:
PHP Fatal error:  Uncaught Error: Call to a member function newBuilder() on null in /vendor/consolidation/robo/src/Common/BuilderAwareTrait.php:43

Fix BuilderAwareTrait.php to prevent Fatal Error

---

src/Common/ExecCommand.php
src/Task/Base/ParallelExec.php

Use Process::fromShellCommandline when constructing a Process object from a command string.

---

src/Task/Development/SemVer.php
tests/integration/SemVerTest.php

Issue description: 959
Remove the check that a given filename is writeable, since this requires the file to exist beforehand.
We dont expect the file to exist however. Therefore this check should not be made, or create a file if failing.
Since this check is included in file_put_contents anyway we may remove the check safely.
I added a test for this issue as well.

Create a semver file if using the SemVer task for the first time

---

docs/tasks/Archive.md
src/Task/Archive/Pack.php
tests/integration/PackExtractTest.php

- [x ] Has tests that cover changes
- [ x] Adds or fixes documentation
Related to #961, allows to filter patterns when creating an archive.
Files or folders could be excluded by using patterns, it's a good way to clean your package before delivery without touching you project folder tree.
```php
<?php
$this->taskPack(<archiveFile>)
->add('project') 
->exclude(['dir/*.zip', '*.md'])
->run();
```
Good to know :
Zip allows regexp, glob or string, @see https://symfony.com/doc/current/components/finder.html#file-name. 
Tar, gz and bz2 allow only regexp @see https://pear.php.net/package/Archive_Tar/docs/latest/Archive_Tar/Archive_Tar.html#methodsetIgnoreList.

Add ignorelist to pack command.

---

tests/integration/CommandTesterTest.php

Removes test which greatly reduces time of test completion, and it doesn't really add value.

Don't use try:exec for testing the CommandTester trait.

---

.scenarios.lock/symfony4/composer.json
.scenarios.lock/symfony4/composer.lock
LICENSE
composer.json
composer.lock
src/Common/IO.php
src/Common/SaveIOStateTrait.php
src/Contract/IOAwareInterface.php
tests/integration/CommandTesterTest.php
tests/integration/RunnerTest.php

#966 / #968 were actually fairly dangerous, as they could corrupt the current commandfile instance state. This is an attempt to rectify that.
@lpeabody : Do you have any idea why CommandTesterTest takes 10s to run? None of the other tests take so long. It seems that all of the time is in the `execute` method. Have not traced it beyond that.

Support saving and restoring state.
