consolidation/Robo

.travis.yml
composer.json
composer.lock
src/Task/Gulp/Base.php
src/Task/Gulp/Run.php
src/Task/Gulp/loadTasks.php
src/Tasks.php
tests/unit/GulpTest.php

it adds the taskGulpRun(), which runs gulp-tasks.
Yes, it looks like taskrunnerception, but there are projects split in frontend and backend and grunt / gulp are quite nice for frontend-task.
with something like:
```
public function gulptest($task='default'){
$this->taskGulpRun();
$this->taskGulpRun($task)->color()->simple()->run();
}
```

Added gulp task

---

src/Common/CommandArguments.php
src/Common/ExecOneCommand.php

To be able to use it stand-alone.
For details, see https://github.com/Codegyre/Robo/issues/105#issuecomment-71763526
fixes #105

Split off trait CommandArguments from ExecOneCommand

---

src/Task/ApiGen/ApiGen.php
src/Task/Base/SymfonyCommand.php
src/Task/Base/Watch.php
src/Task/CommandStack.php
src/Task/Composer/Base.php
src/Task/Development/PackPhar.php
src/Task/File/Concat.php
src/Task/File/Write.php
src/Task/File/loadTasks.php
src/Task/FileSystem/BaseDir.php
src/Task/FileSystem/FilesystemStack.php
src/Task/FileSystem/loadTasks.php
src/Task/Npm/Base.php
src/Task/Testing/Codecept.php
src/Task/Vcs/GitStack.php
src/Task/Vcs/loadTasks.php

Initially only wanted to fix the return doc in `taskFilesystemStack`, but then ran the PhpStorm Inspections and cleaned the obvious (I hope so) ones.

Phpdoc / imports cleanup

---

src/Task/File/Write.php

I added docblocks and refactored place() to use replace() internally.

New methods replace() and regexReplace()

---

src/Task/Assets/Minify.php

Making it possible to pass options to the JS minification.

---

src/Task/Base/Exec.php

The title describes everything...

Adds environment support to Exec task

---

docs/tasks/File.md
src/Task/File/Replace.php

I switched the arguments
and I added the array type to the arguments
I regenerated the docu there is a "non related" change in the bottom, is this correct, too?

fix PR #128 document replaceInFile with better example

---

src/Common/TaskIO.php
src/Task/Assets/Minify.php

It also fixes a division by zero error when an empty file was minified.

Displays the file size for the minified assets.

---

src/Task/Docker/Base.php
src/Task/Docker/Pull.php
src/Task/Docker/Remove.php

Robo\Task\Docker\Remove::getCommand()
same for Pull

fix getCommand, add abstract method

---

src/Task/Vcs/GitStack.php
tests/unit/GitTest.php

I need it. Maybe someone else :)

added "git tag" task

---

src/Task/Assets/Less.php

Less Task Bugfixes

---

src/Task/Assets/Less.php

Given:
```
//styles.less
@import "mixins.less"
```
```php
//RoboFile.php
$this->taskLess(['css/styles.less' => 'css/styles.css'])
->compiler('lessphp')
->run();
```
This will fail since `lessphp` is unable to find imported file even if it is in same dir as `styles.css`.
This PR adds ability to specify `importDir` option for `lessphp` (string or array):
```php
$this->taskLess(['css/styles.less' => 'css/styles.css'])
->compiler('lessphp', ['importDir' => 'css'])
->run();
```
or
```php
$this->taskLess(['css/styles.less' => 'css/styles.css'])
->compiler('lessphp', ['importDir' => ['css', 'less']])
->run();
```

Add ability to set import dir for less compilers

---

src/Task/Assets/CssPreprocessor.php
src/Task/Assets/Less.php
src/Task/Assets/Scss.php
src/Task/Assets/loadTasks.php

Extract common functionality from Scss and Less classes to CssPreprocessor abstract class.
Fixes #205.

Refactoring in Less and Scss tasks

---

started/index.html

Corrected a small spelling error

Small spelling correction to documentation

---

src/Runner.php

Also I'd propose to make separate command for initializing RoboFile to avoid annoying prompt if one doesn't exist. Would it be useful?
This PR fixes #130.

Make Robo not die if no RoboFile available.

---

src/Runner.php

These change allows to make myRobo packages easier. 
Full b/c, no problems are expected, anyway I changed the version to 0.6.0 because this is a new feature
none
In further versions of Robo I had to copy code from the runner.php to make it act and work with a custom RoboClass and custom RoboFile-Name. Now I can create my package just with setting the Robo package as dependency and create my own runner.php with extending \Robo\Runner. The 2nd step is to create a Task.php and extend \Robo\Tasks and add my tasks. So I have all what Robo has plus my tasks easily as a package available. 
I hope that does makes sense for others too. Anyone can check how I did it here (is WIP ofc): https://github.com/rdeutz/jrobo/tree/development

using class variables instead of constants

---

RoboFile.php
src/Task/Development/OpenBrowser.php
src/Task/Development/loadTasks.php

This task allows to open a web browser with one or more urls. (#225)
```php
//open one url
$this->taskOpenBrowser('http://robo.li')->run();
//open more urls:
$this->taskOpenBrowser([
'http://robo.li',
'https://github.com/Codegyre/Robo'
])->run();
```

added OpenBrowser task

---

GeneratedWrapper.tmpl
RoboFile.php
docs/tasks/FileSystem.md
src/Task/FileSystem/FilesystemStack.php
src/Task/StackBasedTask.php
src/Task/WrapperTask.php

This PR introduces a new base task, WrapperTask, to make it easier to create Robo tasks from existing PHP class libraries.  FilesystemStack is ported to use it as an example.  See comments in the file for more details on usage. 
Merged in #251 again, so that tests will pass.

Wrapper task

---

src/Result.php

Allow Result objects to be used in `foreach`.

Add IteratorAggregate to Result.

---

RoboFile.php
docs/collections.md
docs/index.md

Just getting started here; will continue with additional information.

Beginning of Collections documentation

---

docs/tasks/Testing.md
src/Task/Testing/Atoum.php
src/Task/Testing/loadTasks.php
tests/unit/Task/AtoumTest.php

This task allows to run [atoum](http://atoum.org/) tests inside robo.
```php
$this->taskAtoum()
->debug()
//->tags("databaseTest")
//->lightReport()
//->tap()
//->files(["path/to/test1.php", "path/to/test2.php"])
->directories('tests/units')
//->configFile("config/dev.php")
//->debug()
->run();
```

add atoum task

---

.editorconfig
CONTRIBUTING.md
RoboFile.php
composer.json
composer.lock

@DavertMik this is just a first stab at #258 
I figure you may have some different preferences on how to handle this but these are my opinions on a fairly simple way to establish the coding standards and provide a little bit of help for folks to easily follow them. I am not sure if the Sniffer's implimentation of PSR-2 will have similar issues to those @greg-1-anderson mentioned. When I ran the sniff on the entire src directory it threw up a lot of issues so it is possible it is misconfigured out of the box. I like that this can just be included in dev dependencies and most of it is self-contained with the project.

Code standards

---

composer.json
composer.lock
src/Application.php
src/TaskInfo.php
tests/_data/TestedRoboFile.php

Also, add @aliases and @usage annotations.
Needed for Drush integration.

Use phpdocumentor/reflection-docblock to parse docblock comments

---

RoboFile.php

Fix sniffer

---

RoboFile.php
src/Task/Development/Changelog.php
src/Task/Development/GitHub.php
src/Task/Development/GitHubRelease.php

Value input should be done in the command.
Alternative to #296.

Remove calls to 'ask' in tasks.

---

src/Task/File/Write.php
tests/cli/WriteFileCest.php

Useful for setting up configuration files where the desired configuration may or may not already exist in the file.

Add Write::appendIfMatches() and appendUnlessMatches() for taskWriteToFile.

---

RoboFile.php
composer.lock
src/Collection/CollectionProcessHook.php
src/Result.php
src/Runner.php

If a Robo command returns a Collection or TaskInterface, then use a process hook to run it automatically. If a Robo Result contains an 'output' element in its data, then print the result (after applying formatters, if applicable).
This will conflict with #309, but I'll merge them when it's time.

Process collections/tasks returned from commands

---

RoboFile.php
src/Log/ResultPrinter.php
src/Result.php
src/Task/Development/GenerateTask.php
src/Task/Development/GeneratedWrapper.tmpl
src/Task/Development/loadTasks.php
tests/_helpers/CliHelper.php
tests/cli/GenTaskCest.php

Refactor generate:task command into a task.

---

src/Contract/SimulatedInterface.php
src/Task/Base/Exec.php
src/Task/Simulator.php

The Simulated interface allows tasks to print the calculated result of the operation they would preform when run in simulated mode.

Add a SimulatedInterface 

---

CHANGELOG.md
README.md
RoboFile.php
composer.json
src/Runner.php

Changelog for Robo 1.0.0-beta1. Also changes the version to 1.0.0-beta, and the branch alias to 1.x-dev.

Robo 1.0.0-beta1

---

src/Common/InflectionTrait.php
src/Common/TaskIO.php
src/Contract/InflectionInterface.php
src/Task/Archive/Extract.php
src/Task/BaseTask.php
src/Task/Development/Changelog.php
src/Task/Development/GenerateMarkdownDoc.php
src/Task/FileSystem/FilesystemStack.php
src/Task/FileSystem/TmpDir.php

Instead, use InflectionInterface to pass dependencies to subtasks.
See:  https://mwop.net/blog/2016-04-26-on-locators.html

Remove reference to container in BaseTask

---

src/Task/Archive/Pack.php

- don't silently skip dot files
- replace Windows slashes for cross-platform friendly result

Improved pack to zip logic

---

RoboFile.php
robo
src/Runner.php
src/Task/Filesystem/CopyDir.php
tests/unit/RunnerTest.php

Were the coverage options deliberately or accidentally removed from the 'test' command?  --coverage is used in .travis.yml; this is causing tests to fail.

Increase coverage

---

src/Config.php
tests/_helpers/CliHelper.php
tests/_helpers/CodeHelper.php
tests/unit/RunnerTest.php

Further adventures in adding tests

Code coverage

---

composer.lock
tests/unit/RunnerTest.php

Status code may vary from a bad 'ls'; which may be O.S. dependent. Travis returns a different value.
It's kind of odd, really; I merged a passing PR into master, and  it started failing here. Change in behavior on Travis?

Be more flexible about result code returned in test

---

docs/collections.md

These changes were already made in the code.

Bring collections documentation up-to-date 

---

docs/tasks/Vcs.md
src/Task/Archive/loadTasks.php
src/Task/Vcs/HgStack.php
src/Task/Vcs/loadShortcuts.php
src/Task/Vcs/loadTasks.php
tests/unit/Task/HgTest.php

Added tests, tasks, and documentation for Mercurial

Add hg support

---

src/Task/Base/Watch.php

Updating Namespace for Watch task, refering to Lurker\ResourceWatcher\ResourceWatcher
Relates to Issue #363

Updating Namespace reference in Watch task

---

RoboFile.php

Phar improv

---

.travis.yml
composer.json
composer.lock
tests/unit/OutputTest.php

Update to codeception/aspect-mock ~1, and dev-master of codeception/verify to get license files for the last couple of components that are missing them.
This should make VersionEye come back green.

Fix versioneye

---

src/Task/Docker/Base.php
src/Task/Docker/Run.php
tests/unit/Task/BehatTest.php
tests/unit/Task/ComposerTest.php
tests/unit/Task/DockerTest.php
tests/unit/Task/GulpTest.php

Expand composer test, add docker tests.

Moar tests

---

src/Collection/CollectionBuilder.php
src/TaskAccessor.php
src/Tasks.php
tests/_helpers/CliHelper.php
tests/_helpers/CodeHelper.php
tests/_helpers/SeeInOutputTrait.php
tests/cli/SimulatedCest.php

Enhance cli tests to support 'seeInOutput' assertions. Fix bug in managing state (e.g. simulated) in a collection builder.

Add simulated test. 

---

docs/extending.md
docs/framework.md
docs/getting-started.md
docs/index.md
docs/packaging.md

Documentation on extending / packaging Robo and Robo-based scripts.

---

src/Robo.php
src/Runner.php
tests/src/RoboFileFixture.php
tests/unit/RunnerTest.php

Also add tests to ensure that verbosity is being set correctly by Symfony Console, and a couple other Runner tests.

Fix verbosity bugs, 

---

src/Application.php
src/Config.php
src/GlobalOptionsEventListener.php

Clean up Config class initialization / global input option handling.

---

docs/framework.md
src/Robo.php
src/Runner.php
tests/unit/RunnerTest.php

Not sure if this is enough of an improvement.  Just going to put this here for now and think about it. Comments welcome.

Create Robo::run() static wrapper method.

---

composer.lock
src/Robo.php

Print error message using the logger's error() method.

Define an error-displaying function

---

src/Task/Assets/ImageMinify.php

Solves undefined function bug when calling taskImageMinify

---

composer.lock
examples/RoboFile.php
src/Robo.php
tests/_helpers/SeeInOutputTrait.php
tests/cli/_bootstrap.php
tests/unit/ApplicationTest.php

It is important to not pull anything from the container until the client has had a chance to make any desired modifications to it, as changes will not affect any objects already constructed.

Fix bug in container construction

---

src/ResultData.php

PHP Notice:  Use of undefined constant EXITCODE_USER_CANCEL - assumed 'EXITCODE_USER_CANCEL' in .../src/ResultData.php on line 82

FIX notice

---

src/Common/ProgressIndicatorAwareTrait.php
src/Task/ApiGen/ApiGen.php
src/Task/Development/loadTasks.php

Fix type hints in PhpDocs - Part 2

---

docs/framework.md

fix documentation for framework usage

[DOC] Use namspaced Robo\Robo in framework

---

src/Task/Development/GenerateMarkdownDoc.php

- [ x] Fixes a bug
Fixed documenting class properties

[Generate Markdown] fix on processing class properties (trim removed)

---

src/Task/Testing/Behat.php
tests/unit/Task/BehatTest.php

Behat doesn't have run command, so i deleted it.
Fixes issue with Behat.

Fix Behat command

---

docs/framework.md

This pull request adds an example application to framework.md

Update framework.md with example application.

---

README.md
tests/cli/PackExtractCept.php
tests/unit/Common/CommandArgumentsTest.php
tests/unit/Task/ApiGenTest.php
tests/unit/Task/GitTest.php
tests/unit/Task/RsyncTest.php

Alter tests so that they pass on Windows via AppVeyor.

Update CommandArgumentsTest for Windows.

---

composer.lock

Just updating dependencies to get latest annotated-command.

Update to annotated-command 2.4.1, for option arrays.

---

src/Common/CommandArguments.php

Make rawArg() chainable for taskExec().

---

src/Task/Composer/Base.php

- [ X ] Fixes a bug
Can not run composer over ssh

Composer tasks not implement CommandInterface

---

composer.json

... for description of suggested package natxet/CssMin
Just a typo.

fix c&p typo in composer.json

---

src/Task/Base/loadTasks.php

fix phpDoc

---

composer.json
docs/collections.md
examples/RoboFile.php
src/Collection/CallableTask.php
src/Collection/Collection.php
src/Collection/CollectionBuilder.php
src/Collection/CollectionInterface.php
src/Common/ExecTrait.php
src/ResultData.php
src/State/Consumer.php
src/State/Data.php
src/State/StateAwareInterface.php
src/State/StateAwareTrait.php
tests/_helpers/CliHelper.php
tests/_helpers/CliHelperTasks.php
tests/cli/CollectionCest.php
tests/src/Task/CollectionTestTask.php
tests/src/Task/CountingTask.php
tests/src/Task/PassthruTask.php
tests/src/Task/ValueProviderTask.php
tests/unit/Common/ResultDataTest.php
tests/unit/Task/CollectionTest.php

Provide a system to allow state from the result from one task to be used to configure the setters of a following task.

Implement a state system for task collections.

---

docs/tasks/ApiGen.md
docs/tasks/Base.md
docs/tasks/Bower.md
docs/tasks/Composer.md
docs/tasks/Development.md
docs/tasks/Docker.md
docs/tasks/Gulp.md
docs/tasks/Npm.md
docs/tasks/Remote.md
docs/tasks/Testing.md
src/Common/CommandArguments.php
src/Config/Config.php
src/Robo.php
src/Task/Composer/Base.php
src/Task/Composer/Config.php
src/Task/Composer/CreateProject.php
src/Task/Composer/DumpAutoload.php
src/Task/Composer/Init.php
src/Task/Composer/Remove.php
src/Task/Composer/RequireDependency.php
src/Task/Composer/Validate.php
src/Task/Composer/loadTasks.php
src/Task/Vcs/GitStack.php
tests/src/Traits/Common/AdjustQuotes.php
tests/unit/Task/ComposerTest.php
tests/unit/Task/GulpTest.php

Adds tasks for composer init, composer configure, composer require, composer create-project.

Add composer init task, and general composer rounding out.

---

docs/tasks/Filesystem.md
src/Task/Filesystem/CopyDir.php
tests/_data/claypit/some/deeply/nested/structu1.re
tests/_data/claypit/some/deeply/nested/structu2.re
tests/_data/claypit/some/deeply/nested/structu3.re
tests/_data/claypit/some/deeply/nested2/structu21.re
tests/_data/claypit/some/deeply/nested3/nested31/structu311.re
tests/_data/claypit/some/deeply/nested3/structu31.re
tests/_data/claypit/some/deeply/nested3/structu32.re
tests/_data/claypit/some/deeply/nested4/nested41/structu411.re
tests/_data/claypit/some/deeply/nested4/nested41/structu412.re
tests/cli/CopyDirRecursiveExcludeCept.php

Copydir exclude subfolders

---

composer.json
composer.lock
robo.yml
src/Common/ConfigAwareTrait.php
src/Config/Config.php
src/Config/GlobalOptionDefaultValuesInterface.php
src/Contract/ConfigAwareInterface.php
src/GlobalOptionsEventListener.php
src/Robo.php
src/Runner.php
src/Task/Composer/Base.php
tests/unit/ConfigurationInjectionTest.php

A coding convention bug, anyway.

Inject option default values in help (#607). Also, code to ConfigInterface rather than concrete class.

---

.travis.yml
composer.json
composer.lock

Automatically update dependencies via a Travis cron job.

If called from a Travis cron job, then run composer-lock-updater

---

.travis.yml
composer.lock

Fix up tests for php 5.5.

---

.travis.yml
composer.json
composer.lock

```
Loading composer repositories with package information
Updating dependencies
Package operations: 0 installs, 8 updates, 0 removals
- Updating symfony/process (v3.3.8 => v3.3.9): Loading from cache
- Updating symfony/debug (v3.3.8 => v3.3.9): Downloading (100%)
- Updating phpdocumentor/reflection-common (1.0 => 1.0.1): Downloading (100%)
- Updating symfony/finder (v3.3.8 => v3.3.9): Loading from cache
- Updating symfony/event-dispatcher (v3.3.8 => v3.3.9): Loading from cache
- Updating symfony/filesystem (v3.3.8 => v3.3.9): Loading from cache
- Updating symfony/console (v3.3.8 => v3.3.9): Downloading (100%)
- Updating symfony/yaml (v3.3.8 => v3.3.9): Loading from cache
Writing lock file
Generating autoload files
```

Update Composer dependencies (2017-09-16-17-45)

---

composer.json
composer.lock

Pin natxet/cssmin, as the latest version of that package changes default behavior, breaking tests.

Update to latest deps.

---

.gitattributes
appveyor.yml

Added .gitattributes file.
https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production/

Add .gitattributes file

---

.travis.yml

It may be necessary to clear the - common - Travis cache with a to-be-deleted PR!!

Vendor caching may break tests

---

src/Task/Development/GenerateMarkdownDoc.php

Added support for documenting traits in GenMarkdown task

Added support for documenting traits

---

.gitattributes

ignore links to tests folder on export

---

.gitattributes
CHANGELOG.md
composer.json
composer.lock
scenarios/symfony2/composer.json
scenarios/symfony4/composer.json
scenarios/symfony4/composer.lock

Ignore the entirety of the scenarios directory in exports.

Prepare for Ignore all of scenarios directory in exports.

---

dependencies.yml

Update dependencies.yml to work with the new v2 preview.
@greg-1-anderson I thought I would just send you this in a PR for convenience. Thanks for your feedback!

Dependencies.io config for version 2 preview

---

.travis.yml
composer.json
phpunit.xml

Szepeviktor patch 2

---

robotheme/home.html

Fixed installation guide on site main page.

Fixed installation guide on site main page

---

composer.lock
docs/framework.md
robo
scenarios/symfony4/composer.lock
src/Runner.php

Improved the 'robo as a framework' docs

Improve 'Robo as a Framework' starter example; recommend g1a/starter.

---

composer.lock
scenarios/symfony4/composer.lock
src/Config/Config.php

Fixed a bug in config overlay in consolidation/config (1.0.11). It now works better to use that class as-is.

Remove config overlay workaround.

---

README.md

Fix link url.
Currently link pointed to not existed file.

Actualize RoboFile of Codeception project link url in RADME.php

---

src/Common/ExecTrait.php
src/Task/Base/Exec.php
tests/cli/ExecCest.php

Ensure that environment variables are preserved in Exec #768

---

docs/collections.md

- removes a single word to make the sentence more readable.

Minor grammatical Change

---

.scenarios.lock/symfony2/composer.json
.scenarios.lock/symfony4/composer.json
.scenarios.lock/symfony4/composer.lock
LICENSE
composer.json
composer.lock
examples/src/Robo/Plugin/Commands/StdinCommands.php
src/Robo.php

Support StdinHandler from annotated command library (which has tests for it)

Add StdinHandler to the standard Robo DI container

---

.scenarios.lock/symfony2/composer.json
.scenarios.lock/symfony4/composer.json
.scenarios.lock/symfony4/composer.lock
LICENSE
composer.json
composer.lock
examples/src/Robo/Plugin/Commands/ExampleCommands.php
tests/src/RoboFileFixture.php
tests/unit/RunnerTest.php

Test to ensure that upgrade to Annotated Command 2.10.2 fixes a bug.

Failing test fixed by Annotated Command 2.10.2 upgrade

---

.scenarios.lock/symfony2/composer.json
.scenarios.lock/symfony4/composer.json
.scenarios.lock/symfony4/composer.lock
LICENSE
composer.json
composer.lock
src/Common/ConfigAwareTrait.php
src/Contract/ConfigAwareInterface.php

ConfigAware* moving to Consolidation/Config

Extend ConfigAwareTrait from consolidation config

---

composer.json
src/Task/Assets/Minify.php

Rename suggested package »natxet/CssMin« to avoid Composer warnings/errors.
See #876

20190603 rename cssmin package suggestion

---

src/Result.php

Update PHPDoc mismatch

---

docs/getting-started.md

This is in response to #871 and #870.  Simple modification to the getting started documentation, to make it a little more clear what the `--load-from` option can be used for.
This is my first PR for this project, so please be gentle.

Clearer explanation of --load-from option.

---

README.md

Updated README with command for initiating a RoboFile

Updated README with command for initiating a RoboFile

---

src/Symfony/IOStorage.php

Add necessary accessors to IOStorage class.

Add accessors for input() and output() in IOStorage

---

src/Common/IO.php
src/Robo.php
src/Symfony/SymfonyStyleInjector.php
src/Task/Assets/Scss.php
tests/src/RoboFileFixture.php
tests/unit/RunnerTest.php

Move a couple of PRs over from the 1.x branch.

Forward port

---

src/Config/Config.php

Unused property: $defaults

---

src/Collection/CollectionBuilder.php

`\RuntimeException`
props. @phpstan

RuntimeException used relatively

---

src/Task/Assets/ImageMinify.php

Old variables in ImageMinify

---

src/Task/Development/SemVer.php

extract() is not fit for static analysis by @phpstan
-

extract() is not our friend

---

README.md

Change indentation in README example.

Fix incosistent white space formatting in code example.

---

src/Common/ExecTrait.php

Fixed #922: PHP 7.4 compatibility. (#923)

---

.scenarios.lock/symfony4/composer.json
.scenarios.lock/symfony4/composer.lock
LICENSE
composer.json
composer.lock
src/Common/IO.php
src/Contract/OutputAwareInterface.php

This PR is aiming towards increasing testability by allowing Symfony's command tester to work.

Use inject-input-output PR from consolidation/annotated-commands

---

docs/tasks/File.md
src/Task/File/Replace.php

Typo fix in the documentation

---

docs/tasks/Composer.md
src/Task/Composer/CheckPlatformReqs.php
src/Task/Composer/loadTasks.php
tests/unit/Task/ComposerTest.php

Adds a new CheckPlatformReqs Composer task.
This task calls `composer check-platform-reqs`, which is now a recommended deploy step with Composer 2: https://github.com/composer/composer/blob/2.0.0-alpha1/doc/07-runtime.md#platform-check

New CheckPlatformReqs task
